In [1]:
import numpy

arr = numpy.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [2]:
import numpy

arr = numpy.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [7]:
import numpy as np


arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])
arr = arr1 + arr2
print(arr)

[ 3  7 11]
